version: '3'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgres
    environment:
      POSTGRES_USER: clientes
      POSTGRES_PASSWORD: vlc123
      POSTGRES_DB: clientes_db
    networks:
      - clientes-compose-network
    restart: always
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    networks:
      - clientes-compose-network
    links:
      - db
    ports:
      - "8081:8080"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: vinicius/clientes:1.0
    links:
      - db
    networks:
      - clientes-compose-network
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  dbdata:

networks:
  clientes-compose-network:
    driver: bridge